"""alterando tabelas

Revision ID: 314150bcf563
Revises: 472b03bc3921
Create Date: 2024-09-16 11:41:40.465874

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "314150bcf563"
down_revision: Union[str, None] = "472b03bc3921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("debits", "category_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("debits", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("debits", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("debits", "category_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
