"""pequenas correcoes nos models

Revision ID: 7f72adeb9bf9
Revises: 472b03bc3921
Create Date: 2024-09-16 21:02:04.196081

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f72adeb9bf9"
down_revision: str | None = "472b03bc3921"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("debits", "category_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("debits", "owner_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("debits", "owner_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("debits", "category_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
