"""pequenas correcoes nos models

Revision ID: 97caf4e2d20c
Revises: 7f72adeb9bf9
Create Date: 2024-09-16 22:19:22.643034

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "97caf4e2d20c"
down_revision: str | None = "7f72adeb9bf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
