"""adiciona url profile

Revision ID: d5d566da101e
Revises: 8db276b592eb
Create Date: 2024-09-19 20:51:24.527149

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5d566da101e"
down_revision: Union[str, None] = "8db276b592eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_photo_url", sa.String(length=500), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_photo_url")
    # ### end Alembic commands ###
